version: '2'
services:
  base:
    image: node:10-jessie-slim
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build